services:
  app:
    # behövs det en punkt nedanför i build? eller är det bara nödvändligt vid Dockerfile?
    build: .
    ports:
      - "8080:8080"
    environment:
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_SECRET_KEY=${CLOUDINARY_SECRET_KEY}
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: